common/models/AuctionRate.php
<?php

namespace common\models;

use Yii;
use yii\behaviors\TimestampBehavior;
use yii\behaviors\BlameableBehavior;
/**
 * This is the model class for table "auction_rate".
 *
 * @property string $id
 * @property string $auction_lot_id
 * @property string $rate_amount
 * @property string $rate_time
 * @property string $created_at
 * @property string $created_by
 * @property string $updated_at
 * @property string $updated_by
 *
 * @property AuctionLot $auctionLot
 * @property User $createdBy
 * @property User $updatedBy
 */
class AuctionRate extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'auction_rate';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['auction_lot_id', 'rate_time', 'created_at', 'created_by', 'updated_at', 'updated_by'], 'integer'],
            [['rate_amount', 'rate_time'], 'required'],
            [['rate_amount'], 'number']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'Идентификатор записи',
            'auction_lot_id' => 'Лот',
            'rate_amount' => 'Сумма ставки',
            'rate_time' => 'Время ставки',
            'created_at' => 'Дата и время ставки',
            'created_by' => 'ФИО пользователя',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAuctionLot()
    {
        return $this->hasOne(AuctionLot::className(), ['id' => 'auction_lot_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCreatedBy()
    {
        return $this->hasOne(User::className(), ['id' => 'created_by']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUpdatedBy()
    {
        return $this->hasOne(User::className(), ['id' => 'updated_by']);
    }

    public function behaviors()
    {
        return [
            [
                'class' => BlameableBehavior::className(),
                'createdByAttribute' => 'created_by',
                'updatedByAttribute' => 'updated_by',
            ],
            [
                'class' => TimestampBehavior::className(),
                'createdAtAttribute' => 'created_at',
                'updatedAtAttribute' => 'updated_at',
            ],
        ];
    }
}

backend/controllers/AuctionrateController.php
<?php

namespace backend\controllers;

use Yii;
use yii\filters\AccessControl;
use common\components\AccessRule;
use common\models\User;
use common\models\AuctionRate;
use common\models\AuctionRateSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * AuctionrateController implements the CRUD actions for AuctionRate model.
 */
class AuctionrateController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'ruleConfig'=>['class' => AccessRule::className(),],
                'only' => ['index', 'create', 'update', 'delete', 'view'],
                'rules' => [
                    [
                        'actions' => ['index', 'create', 'update', 'delete', 'view'],
                        'allow' => true,
                        'roles' => [User::ROLE_ADMIN]
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all AuctionRate models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new AuctionRateSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single AuctionRate model.
     * @param string $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new AuctionRate model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new AuctionRate();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing AuctionRate model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing AuctionRate model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the AuctionRate model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $id
     * @return AuctionRate the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = AuctionRate::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

backend/controllers/UserController.php
<?php

namespace backend\controllers;

use Yii;
use yii\filters\AccessControl;
use common\components\AccessRule;
use common\models\User;
use common\models\UserSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * UserController implements the CRUD actions for User model.
 */
class UserController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'ruleConfig' => ['class' => AccessRule::className(),],
                'only' => ['index', 'create', 'update', 'delete', 'view', 'changeactive'],
                'rules' => [
                    [
                        'actions' => ['index', 'create', 'update', 'delete', 'view', 'changeactive'],
                        'allow' => true,
                        'roles' => [User::ROLE_ADMIN]
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all User models.
     * @return mixed
     */

    public function actionChangeactive($id)
    {
        $model = $this->findModel($id);
        if ($model->role != User::ROLE_ADMIN) {
            $model->status = $model->status == User::STATUS_DELETED ? User::STATUS_ACTIVE : User::STATUS_DELETED;
            $model->save();
        }
        return $this->redirect(['view', 'id' => $id]);
    }

    public function actionIndex()
    {
        $searchModel = new UserSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single User model.
     * @param string $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Updates an existing User model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing User model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $model = $this->findModel($id);
        if ($model->role != User::ROLE_ADMIN) {
            $model->status = User::STATUS_DELETED;
            $model->save();
        }
        return $this->redirect(['index']);
    }

    /**
     * Finds the User model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $id
     * @return User the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = User::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

backend/views/auctionrate/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\AuctionRate */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="auction-rate-form">

    <?php $form = ActiveForm::begin([
        'options'=>['class'=>'form'],
        'fieldConfig' => [
            'template' => '{input}{label}{hint}{error}',
            'options' => ['class' => 'form-group floating-label'],
            'labelOptions' => [],
            'inputOptions' => ['class' => 'form-control'],

        ]]); ?>
    <?= $form->field($model, 'auction_lot_id')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'rate_amount')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'rate_time')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'created_at')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'created_by')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'updated_at')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'updated_by')->textInput(['maxlength' => true]) ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Создать' : 'Сохранить', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/auctionrate/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\AuctionRateSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="auction-rate-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'auction_lot_id') ?>

    <?= $form->field($model, 'rate_amount') ?>

    <?= $form->field($model, 'rate_time') ?>

    <?= $form->field($model, 'created_at') ?>

    <?php // echo $form->field($model, 'created_by') ?>

    <?php // echo $form->field($model, 'updated_at') ?>

    <?php // echo $form->field($model, 'updated_by') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/auctionrate/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model common\models\AuctionRate */

$this->title = 'Добавление ' .'Auction Rate';
$this->params['breadcrumbs'][] = ['label' => 'Список ставок', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<!--<div class="--><!---create">-->

<!--    <h1>--><!--Html::encode($this->title) ?></h1>-->

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

<!--</div>-->

backend/views/auctionrate/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use common\models\User;

/* @var $this yii\web\View */
/* @var $searchModel common\models\AuctionRateSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Список ставок';
$this->params['breadcrumbs'][] = $this->title;
?>
<!--<div class="row">
    <div class="col-lg-12">
    <?php /*// echo $this->render('_search', ['model' => $searchModel]); */ ?>
        <? /*= Html::a('Create Auction Rate', ['create'], ['class' => 'btn ink-reaction btn-raised btn-primary']) */ ?>
    </div>
</div>-->
<div class="row">
    <div class="col-lg-12">
        <?= GridView::widget([
            'dataProvider' => $dataProvider,
            'filterModel' => $searchModel,
//            'filterModel' => null,
            'layout' => '{items}{summary}{pager}',
            'tableOptions' => ['class' => 'table table-hover'],
            'columns' => [
                ['class' => 'yii\grid\SerialColumn'],
                [
                    'attribute' => 'created_by',
                    'filter' => User::get_users(),
                    'format' => 'raw',
                    'value' =>
                        function ($model) {
                            return Html::a($model->createdBy->fio, ['user/view', 'id' => $model->createdBy->id],
                                ['class' => 'btn ink-reaction btn-flat btn-xs btn-primary']);
                        }
                ],
                'createdBy.phone',
                [
                    'attribute' => 'auction_lot_id',
                    'filter' => User::get_users(),
                    'format' => 'raw',
                    'value' => function ($model) {
                        return Html::a($model->auctionLot->name, ['auction/view', 'id' => $model->auctionLot->id],
                            ['class' => 'btn ink-reaction btn-flat btn-xs btn-primary']);
                    }
                ],
                'rate_amount',
                'rate_time:datetime',
                'created_at:datetime',
                /*
                                ['class' => 'yii\grid\ActionColumn',
                                    'headerOptions' => ['width' => '150'],
                                    'template' => '{update} {view} {delete}',
                                    'buttons' => [
                                        'update' => function ($url, $model) {
                                            return Html::a(
                                                '<i class="md-mode-edit"></i>',
                                                $url,
                                                [
                                                    'type' => 'button',
                                                    'class' => 'btn btn-icon-toggle',
                                                    'data-toggle' => 'tooltip',
                                                    'data-placement' => 'top',
                                                    'data-original-title' => 'Редактировать'
                                                ]);
                                        },
                                        'view' => function ($url, $model) {
                                            return Html::a(
                                                '<i class="md-visibility"></i>',
                                                $url,
                                                [
                                                    'type' => 'button',
                                                    'class' => 'btn btn-icon-toggle',
                                                    'data-toggle' => 'tooltip',
                                                    'data-placement' => 'top',
                                                    'data-original-title' => 'Просмотреть'
                                                ]);
                                        },
                                        'delete' => function ($url, $model) {
                                            return Html::a(
                                                '<i class="md-delete"></i>',
                                                $url,
                                                [
                                                    'type' => 'button',
                                                    'class' => 'btn btn-icon-toggle',
                                                    'data-toggle' => 'tooltip',
                                                    'data-placement' => 'top',
                                                    'data-original-title' => 'Удалить запись',
                                                    'data' => [
                                                        'confirm' => 'Вы действительно хотите удалить запись?',
                                                        'method' => 'post',
                                                    ]
                                                ]);
                                        },
                                    ],
                                ],*/
            ],
        ]); ?>

    </div>
</div>

backend/views/auctionrate/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\AuctionRate */

$this->title = 'Update Auction Rate: ' . ' ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Список ставок', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Редактирование';
?>
<!--<div class="-update">

    <h1>Html::encode($this->title) ?></h1>
-->
    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

<!--</div>-->

backend/views/auctionrate/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model common\models\AuctionRate */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Список ставок', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<!--<div class="-view">

    <h1>Html::encode($this->title) ?></h1>
-->
    <p>
        <?= Html::a('Редактировать', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Удалить', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Вы действительно хотите удалить эту запись?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'auction_lot_id',
            'rate_amount',
            'rate_time',
        ],
    ]) ?>
<!--
</div>
-->